### ISSUE TITLE
How to configure QuickCached threads number?

### ISSUE THREAD

**Issue by jiaweixiao** [QuickServerLab/QuickCached#6]
In file 'CommandHandler.java' I find the following commented-out code:
```
		//threads           Number of worker threads requested.
		//stats.put("threads", );
```
Can I configure QuickCached threads number?
If yes, how to do it?

Thanks.

**Comment by akshath** [comment]
you can edit no of threads in conf/QuickCached.xml.. look for <thread-object-pool> tag

**Comment by jiaweixiao** [comment]
thank you for your reply, I saw \<thread-object-pool\> tag in conf/QuickCached.xml
btw, I think no of threads equals no of clients if the pool is large enough according to QuickServer 2.1.0 document:
> In Blocking Mode: A thread is dedicated to every ClientHandler for processing events from the client.
